name: water
description: An implementation of HydratedStorage using Hive, a fast and lightweight key-value database
version: 1.2.0
homepage: https://github.com/arnemolland/water

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^1.6.8
  hydrated_bloc: ^4.0.0
  hive: ^1.4.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
