name: water
description: An implementation of HydratedStorage using Hive, a fast and lightweight key-value database
version: 1.1.0
homepage: https://github.com/arnemolland/water

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^1.5.1
  pedantic: ^1.8.0
  hydrated_bloc: ^3.0.0-dev.1
  hive: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
